# AquaYOLO-m (d=0.67, w=0.75, r=1.5)
# P1=48, P2=96, P3=192, P4=384, P5=576
# Detect: P3=192, P4=384, P5=384

nc: 10

backbone:
  - [-1, 1, AquaResidualBlock, [48, 2]]          # P1/2
  - [-1, 1, AquaResidualBlock, [96, 2]]          # P2/4
  - [-1, 2, C2f,              [96, True]]        # 3*d≈2
  - [-1, 1, AquaResidualBlock, [192, 2]]         # P3/8
  - [-1, 4, C2f,              [192, True]]       # 6*d≈4
  - [-1, 1, AquaResidualBlock, [384, 2]]         # P4/16
  - [-1, 4, C2f,              [384, True]]       # 6*d≈4
  - [-1, 1, AquaResidualBlock, [576, 2]]         # P5/32 (512*w*r)
  - [-1, 2, C2f,              [576, True]]       # 3*d≈2
  - [-1, 1, SPPF,             [576, 5]]

head:
  - [[6, 9],  1, DSAM, []]                       # -> (B,384,40,40)
  - [-1,      2, C2f, [384, False]]              # 3*d≈2

  - [[4, -1], 1, DSAM, []]                       # -> (B,192,80,80)
  - [-1,      2, C2f, [192, False]]              # 3*d≈2   (P3 head)

  - [-1,      1, Conv, [192, 3, 2]]              # -> (B,192,40,40)
  - [[11, -1], 1, DSAM, []]                      # -> (B,384,40,40)
  - [-1,      2, C2f, [384, False]]              # 3*d≈2   (P4 head)

  - [-1,      1, Conv, [384, 3, 2]]              # -> (B,384,20,20)
  - [[9,  -1], 1, DSAM, []]                      # -> (B,576,20,20)
  - [-1,      2, C2f, [384, False]]              # P5 head uses 512*w (=384)

  - [[13, 16, 19], 1, Detect, [nc]]              # ch=[192,384,384]