# AquaYOLO-s (d=0.33, w=0.50, r=2)
# P1=32, P2=64, P3=128, P4=256, P5=512
# Detect: P3=128, P4=256, P5=256

nc: 10

backbone:
  - [-1, 1, AquaResidualBlock, [32, 2]]          # P1/2
  - [-1, 1, AquaResidualBlock, [64, 2]]          # P2/4
  - [-1, 1, C2f,              [64, True]]        # 3*d≈1
  - [-1, 1, AquaResidualBlock, [128, 2]]         # P3/8
  - [-1, 2, C2f,              [128, True]]       # 6*d≈2
  - [-1, 1, AquaResidualBlock, [256, 2]]         # P4/16
  - [-1, 2, C2f,              [256, True]]       # 6*d≈2
  - [-1, 1, AquaResidualBlock, [512, 2]]         # P5/32 (512*w*r)
  - [-1, 1, C2f,              [512, True]]       # 3*d≈1
  - [-1, 1, SPPF,             [512, 5]]

head:
  - [[6, 9],  1, DSAM, []]                       # -> (B,256,40,40)
  - [-1,      1, C2f, [256, False]]              # 3*d≈1
  - [[4, -1], 1, DSAM, []]                       # -> (B,128,80,80)
  - [-1,      1, C2f, [128, False]]              # 3*d≈1   (P3 head)

  - [-1,      1, Conv, [128, 3, 2]]              # -> (B,128,40,40)
  - [[11, -1], 1, DSAM, []]                      # -> (B,256,40,40)
  - [-1,      1, C2f, [256, False]]              # 3*d≈1   (P4 head)

  - [-1,      1, Conv, [256, 3, 2]]              # -> (B,256,20,20)
  - [[9,  -1], 1, DSAM, []]                      # -> (B,512,20,20)
  - [-1,      1, C2f, [256, False]]              # P5 head uses 512*w (=256)

  - [[13, 16, 19], 1, Detect, [nc]]              # ch=[128,256,256]